auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: true
    dir: /var/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

storage_config:
  boltdb:
    directory: /var/loki/index
  filesystem:
    directory: /var/loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  max_streams_per_user: 10000
  allow_structured_metadata: false
  reject_old_samples: false
  creation_grace_period: 168h

